### ISSUE TITLE
DashBoard dont load!

### ISSUE THREAD

**Issue by ITSMijaiL** [Vertex-Client/Vertex-Client-PE#54] opened 2017-04-24 01:24 UTC
The dashboard dont load but it throws an error :/
![screenshot_2017-04-23-21-28-34](https://cloud.githubusercontent.com/assets/27212217/25319420/d84187e6-286b-11e7-9e11-1baf12269a3c.png)

**Comment by Vertex-Client** [comment] 2017-04-24 16:10
Duplicate of #52. Issue will be closed.

**Closed as completed by Vertex-Client** 2017-04-24 16:10 UTC
