### ISSUE TITLE
1.2 with toolbox

### ISSUE THREAD

**Issue by AutoGrind** [Vertex-Client/Vertex-Client-PE#37] opened 2016-09-10 10:42 UTC
I prefer toolbox over block launcher because the mini map and xray with your hacked client is all I need in anarchy servers. Last update wouldn't run with toolbox. This update will run in my world's but not in multi-player. It crashes.

**Comment by Vertex-Client** [comment] 2016-09-10 11:34
Hello there, could you send us a screenshot of the stack trace (crash dialog -> report button -> system information -> stack trace) please? Thanks in advance. 😄

BTW: Please read #34 next time.

**Comment by WRCDesigns** [comment] 2016-09-10 16:58
Where do you find the crash dialog page?
I am having the same problem but I don't know where the report is

**Comment by Vertex-Client** [comment] 2016-09-12 15:34
I tried anything to fix this, but unfortunately I couldn't seem to find the cause and fix it. I found an unrelated bug which I just fixed though.

**Comment by AutoGrind** [comment] 2016-09-14 11:01
Toolbox with v1.2.1
Good: With 1.2.1 I was finally able to add the client and pro activator without Toolbox crashing right away and able to join my own created or downloaded worlds, creative and survival. All the “Hax” that I tried seemed to work. 

Issue-1: I reproduced this on every attempt. This problem happens while in my own created or downloaded worlds, creative and survival. When I hit the (Android, back button) followed by the (Minecraft, Quit to title button) the game sticks or Toolbox crashes.

Issue-2: I reproduced this on every attempt. Im not able to enter my Realm or servers. When I try to join it starts to connect and build then the game sticks or Toolbox crashes. Issue-2 may be 2 separate issues but they behave the same. 

![v1 2 1](https://cloud.githubusercontent.com/assets/21264778/18507818/eebc2f6a-7a3f-11e6-97e8-167f87c7f83a.png)

Issue-1 pics & stack trace: Leaving Worlds
![4](h ttps://cloud.githubusercontent.com/assets/21264778/18508908/3c36cada-7a44-11e6-9283-04ec172142fc.png)
![default](https://cloud.githubusercontent.com/assets/21264778/18508918/4a63534e-7a44-11e6-93a9-f3c35cdcfb9d.png)
![2](https://cloud.githubusercontent.com/assets/21264778/18508934/510a934c-7a44-11e6-9005-4476ce2ce813.png)

Issue-2 pics & stack trace: Realms
![2v1 2 1](https://cloud.githubusercontent.com/assets/21264778/18507830/fa923fc8-7a3f-11e6-8761-7eab66e86752.png)
![3v1 2 1](https://cloud.githubusercontent.com/assets/21264778/18507838/03e78844-7a40-11e6-94db-7f5845c45eb0.png)
![5v1 2 1](https://cloud.githubusercontent.com/assets/21264778/18507937/3affe6d2-7a40-11e6-8f84-523b6224c4d9.png)
![6v 1 2 1](https://cloud.githubusercontent.com/assets/21264778/18507960/4ab9af2c-7a40-11e6-804d-bc5463aa1dc6.png)

Issue-2 pics stack trace: Servers
![default](https://cloud.githubusercontent.com/assets/21264778/18508005/7fb960fa-7a40-11e6-90f6-1fcf79b00ba6.png)
![4](https://cloud.githubusercontent.com/assets/21264778/18508211/4d0f7148-7a41-11e6-8c18-9d71765dfeee.png)
![2](https://cloud.githubusercontent.com/assets/21264778/18508013/8c0f7826-7a40-11e6-852f-87255b2ddff8.png)

Android version: 6.0.1 Marshmallow
Vertex Client PE version: v1.2
MCPE version: 0.15.7
Launcher: Toolbox
Pro: yes
Device: HTC One_M8

This was all done while I knew that Toolbox was able to do all these things without Vertex Client and Pro being active. With out clients and with clients other than Vertex, Toolbox is able to do all things important to me being: connecting to Realms and servers. I use hacked clients for anarchy style servers only, Im not a griefer nor do I cheat in servers such as Mineplex, etc. I prefer Toolbox as my launcher and an older version of Vertex, the one right before the button change. Wish it'd let me use a few versions back, glad it won't be disabling the future older versions anymore. 
                                                                                                                                        ~AutoGrind

**Comment by AutoGrind** [comment] 2016-09-14 11:14
Toolbox with v1.2.1 good then bad:

Good: With 1.2.1 I was able to add the client and pro activator without Toolbox crashing right away. I was also able to join my own created or downloaded worlds, creative and survival. All the “Hax” that I tried seemed to work.

Issue-1: I reproduced this on every attempt. This problem happens while in my own created or downloaded worlds, creative and survival. When I hit the (Android, back button) followed by the (Minecraft, Quit to title button) the game sticks or Toolbox crashes.

Issue-2: I reproduced this on every attempt. Im not able to enter my Realm or servers. When I try to join it starts to connect and build then the game sticks or Toolbox crashes. Issue-2 may be 2 separate issues but they behave the same to me.

Issue-1 pics & stack trace: Leaving Worlds crash
![4](https://cloud.githubusercontent.com/assets/21264778/18510093/433d2814-7a4a-11e6-89c0-1c6958a6f062.png)
![2](https://cloud.githubusercontent.com/assets/21264778/18510510/714bfb52-7a4c-11e6-88a1-c6b59716d91a.png)

Issue 2 pics & stack trace: Realms 
![2v1 2 1](https://cloud.githubusercontent.com/assets/21264778/18510147/7ca06da0-7a4a-11e6-85fb-d1535077df2d.png)
![5v1 2 1](https://cloud.githubusercontent.com/assets/21264778/18510153/881d24fc-7a4a-11e6-8ffe-f34d86e6263d.png)
![6v 1 2 1](https://cloud.githubusercontent.com/assets/21264778/18510158/90bbd946-7a4a-11e6-934b-6070425d2fb8.png)

Issue 2 pics & stack traces: Servers
![default](https://cloud.githubusercontent.com/assets/21264778/18510182/acd5eedc-7a4a-11e6-9536-6ef812302de8.png)
![22](https://cloud.githubusercontent.com/assets/21264778/18510478/49c92ad2-7a4c-11e6-81d5-a3fd9dada4d6.png)
![23](https://cloud.githubusercontent.com/assets/21264778/18510487/5285f628-7a4c-11e6-9e02-71503cd05150.png)

Android version: 6.0.1 Marshmallow
Vertex Client PE version: v1.2
MCPE version: 0.15.7
Launcher: Toolbox
Pro: yes
Device: HTC One_M8

This was all done while I knew that Toolbox was able to do all these things without Vertex Client and Pro being active. With out clients and with clients other than Vertex, Toolbox is able to do all things important to me being: connecting to Realms and servers. I use hacked clients for anarchy style servers only, Im not a griefer nor do I cheat in servers such as Mineplex, etc. 
I prefer Toolbox as my launcher and an older version of Vertex, the one right before the button icon change. Wish it'd let me use a few versions back, glad it won't be disabling the future older versions anymore. 
~AutoGrind

**Comment by Vertex-Client** [comment] 2016-09-14 11:52
Thanks for the screenshots, now that's a real issue, not just 'halp!1!1! Crash' like others do.

**Comment by Vertex-Client** [comment] 2016-09-14 11:54
Hmm, those screenshots tell me that it's a native crash, maybe you could scroll some more to the bottom? It may tell us the (native) function which caused the crash. I think it may be because of the Level.isRemote() function.

**Comment by Vertex-Client** [comment] 2016-09-14 11:56
Thanks though, I will look into it in the next few hours.

**Comment by AutoGrind** [comment] 2016-09-14 23:35
I'll get back to it tonight after work. Heads up Block Launcher updated today

**Comment by AutoGrind** [comment] 2016-09-16 08:55
I was thinking about this today and its definitely native. With native crashes, if their hard to track down, sometimes the bug happens after a garbage collection has disposed of it. Some stacks are caused by incorrect method signatures in the function.. If its not recorded in the stack trace it may be in my system log or event log. I have access to both but there a mile long each and would probably be a couple hundred pics. I can't copy and paste it or I would have by now. I also tried screen recording myself scrolling through it but it would've takin forever. If you know of a way that I can send these reports to you rather than the default recipient ,  "googleplay" I will do it. I think if you have google play and you tried this on an android device with Toolbox you should be able to reproduce the issue and have a similar system and event log to look at. If you know of any apps that record event logs, system logs, and stacks Ill download it. Google doesn't allow you to change or add recipients with the crash report. 
Check this out if you don't have it already. Its 25US and I think it gives you access to that stuff whenever. 
https://play.google.com/apps/publish/ ![screenshot_20160916-042650](https://cloud.githubusercontent.com/assets/21264778/18580003/0a4bdc02-7bc7-11e6-8914-fdc369c55f3c.png)
![screenshot_20160916-042728](https://cloud.githubusercontent.com/assets/21264778/18579995/02e806b6-7bc7-11e6-82b1-4af96bc3d9d4.png)

![screenshot_20160916-042701](https://cloud.githubusercontent.com/assets/21264778/18579999/06247e5e-7bc7-11e6-88a8-31930191ba32.png)

![screenshot_20160916-042728](https://cloud.githubusercontent.com/assets/21264778/18580012/0fcd94fe-7bc7-11e6-8fc7-10ca32514266.png)

**Comment by Vertex-Client** [comment] 2016-09-16 19:39
Status: half fixed, the joining seems to work again, it was caused by VertexClientPE.loadDeathCoords() --> Level.getWorldDir() I think.

**Comment by Vertex-Client** [comment] 2016-09-16 19:42
I will close this issue for now.

**Closed as completed by Vertex-Client** 2016-09-16 19:42 UTC
