### ISSUE TITLE
vertex client problems...

### ISSUE THREAD

**Issue by CemilVDV** [Vertex-Client/Vertex-Client-PE#33] opened 2016-09-04 09:41 UTC
Blocklaunsher: if u join a server Blocklaunsher crashes..
Toolbox:if start the game it gives an error code (u cant use the client).
Another problems is if the new release dobt works we cant use the older version to because it isnt supported anymore , please fix these issues.

**Comment by CemilVDV** [comment] 2016-09-04 09:59
With toolbox coudn't copy the error log (no copy button).

**Comment by CemilVDV** [comment] 2016-09-04 10:00
And im ising mcpe 0.15.6 for vertex

**Comment by DaMatrix** [comment] 2016-09-04 11:51
Can confirm, this needs to be fixed.

**Comment by Vertex-Client** [comment] 2016-09-04 15:50
Duplicate of #31 and #32, closing.

**Comment by CemilVDV** [comment] 2016-09-04 15:52
so what im doing wrong?

**Comment by Vertex-Client** [comment] 2016-09-04 15:53
Nothing, I can confirm this as a bug since many users have it. I only closed this issue since it was a duplicate of #31 and #32, continue the discussion on the #31 page.

**Comment by Vertex-Client** [comment] 2016-09-04 16:07
Send me the stack trace of the BlockLauncher crash (report button on the crash dialog --> system information --> stack trace).

**Comment by CemilVDV** [comment] 2016-09-04 16:08
there is no crash dialog ,it just closes..

**Comment by dausruddin** [comment] 2016-09-07 04:24
Yep. I got same popup on Tollbox with latest release and latest commit. It says something about runtime error and have option to disable script temporarily or just continue. And yes, that error cant be copied.
@Vertex-Client does this script even support toolbox?  Because seems that you are not getting this error, maybe you are on BlockLauncher?. Btw Im using latest toolbox and latest mcpe(not beta).

Edit: This is the errors on latest release (1.1.3) - https://s14.postimg.io/wyo0t5ikv/2016_Sep_07_12_28_23.png

**Comment by Vertex-Client** [comment] 2016-09-07 14:59
There is something weird going on since everything works fine for me and the issue is about a font which should be in the MCPE 0.15.7 apk, please check if it's there. I already fixed it a bit but I don't know the exact cause of the issue. If you send me a screenshot of the information screen (with all the debug info), I may get to find the cause.

**Comment by dausruddin** [comment] 2016-09-07 15:10
How to check the font? I reinstalled the game because I was in beta. I even removed the data in `/sdcard/games/com.mojang` because the game crashed with data from beta.

And, how to produce the debug information? I really dont have any idea, didnt see any option in setting to enable it tho.

**Comment by Vertex-Client** [comment] 2016-09-07 15:34
It should be in the apk, use a backup function (like the one in ES File Explorer).

**Comment by DaMatrix** [comment] 2016-09-07 16:39
why not try adding a new folder (fonts/) and put a ttf of SeogeWP in there? it would be a somewhat ugly, yet functional fix (i think)

**Comment by Vertex-Client** [comment] 2016-09-07 17:10
The apk should include this font by default... I didn't change anything in the apk and I even found it in the 0.15.7 apk.

**Comment by Affannnn** [comment] 2016-09-09 11:23
I Want To Hack Please Fix Fast! Even the font is removing IDC but I need to hack !

**Comment by DaMatrix** [comment] 2016-09-09 12:04
Step 1: download an old version of vertex  (1.1.1)
Step  2: rename it to a .zip file 
Step 3: extract it 
Step 4: find a variable called isSupported  
Step 5: add a line after the part where it is reassigned and set it to true
Step 6: save and use the script

**Comment by Affannnn** [comment] 2016-09-09 12:07
Can You Make A Tutorial I Will See That Vid On Your YT Channel Thx So Much.

**Comment by Affannnn** [comment] 2016-09-09 12:08
And I also need name of channel

**Comment by Vertex-Client** [comment] 2016-09-09 12:24
Changing the isSupported line doesn't help as Vertex Client PE automatically checks for support online. It saves the support to the device data too, so it won't won't work offline either.

**Comment by Vertex-Client** [comment] 2016-09-09 12:25
It's also not allowed to edit Vertex Client PE support related code.

**Comment by Affannnn** [comment] 2016-09-09 12:25
THX for help but I just changed the version 1.1.1 to 1.1.3 and it worked

**Comment by Vertex-Client** [comment] 2016-09-09 12:28
You're not allowed to do that. If you edit something we may have to ban you. I know it doesn't work for Toolbox but you shouldn't edit it anyways. I will add some more security in v1.2 to prevent this.

**Comment by Affannnn** [comment] 2016-09-09 12:30
Ok I Changed It Back Ok Now

**Comment by Vertex-Client** [comment] 2016-09-09 12:31
Okay. We won't ban you (but if you're lying ...).

**Comment by Vertex-Client** [comment] 2016-09-09 12:31
v1.2 will be out today with fixes too.

**Comment by Affannnn** [comment] 2016-09-09 12:34
Thx For Help!

**Closed as completed** 2016-09-10 11:35 UTC
Labels: bug
