### ISSUE TITLE
Vertex 3.1 not loading correctly on the latest version of Minecraft and BlockLauncher (Pro)

### ISSUE THREAD

**Issue by SWPlaysMC** [Vertex-Client/Vertex-Client-PE#75] opened 2019-10-13 13:18 UTC
@Vertex-Client @DaMatrix @Astro36 @peacestorm @xLPMG 
Every time I start a world with "Vertex Client PE.modpkg" enabled, I get this error.
I have downloaded it from the official source, so it is supported.

> org.mozilla.javascript.EcmaError: SyntaxError: Empty JSON string (Vertex_Client_PE.modpkg#207)
> 	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
> 	at org.mozilla.javascript.ScriptRuntime.constructError(Unknown Source)
> 	at org.mozilla.javascript.NativeJSON.parse(Unknown Source)
> 	at org.mozilla.javascript.NativeJSON.execIdCall(Unknown Source)
> 	at org.mozilla.javascript.IdFunctionObject.call(Unknown Source)
> 	at org.mozilla.javascript.Interpreter.interpretLoop(Unknown Source)
> 	at script(Vertex_Client_PE.modpkg:207)
> 	at script(Vertex_Client_PE.modpkg:199)
> 	at org.mozilla.javascript.Interpreter.interpret(Unknown Source)
> 	at org.mozilla.javascript.InterpretedFunction.call(Unknown Source)
> 	at org.mozilla.javascript.ContextFactory.doTopCall(Unknown Source)
> 	at org.mozilla.javascript.ScriptRuntime.doTopCall(Unknown Source)
> 	at org.mozilla.javascript.InterpretedFunction.exec(Unknown Source)
> 	at net.zhuoweizhang.mcpelauncher.ScriptManager.initJustLoadedScript(ScriptManager.java:289)
> 	at net.zhuoweizhang.mcpelauncher.ScriptManager$ParseThread.run(ScriptManager.java:201)
> 	at java.lang.Thread.run(Thread.java:818) -BlockLauncher

Does anyone know what is wrong and how to fix it?
I also have the "[More] MODS" addon, but I am not using it.
ii. How to reproduce:
1. Get from any official link.
2. Wrench>Manage ModPE Scripts>Add the Vertex modpkg file.
3. Verify it is enabled.
4. Now close and restart BlockLauncher
5. Make or start a world and wait.
6. You should see the "Oh noes everything broke" error.
iii. Info.
Device: Amazon Fire 7 running Android version 5.0
MCBE Version: Latest
BlockLauncher (Pro) version: Latest
Vertex Version: Latest (3.1)

**Comment by Vertex-Client** [comment] 2019-10-13 21:17
Could you try the latest dev version to confirm if the issue is fixed, or if it's not report it here? To get it, please follow these instructions:

_1. Go to the Vertex Info screen (long tap VX > Dashboard > Information)._
_2. Scroll down and search the text that says 'Status: normal user'._
_3. Tap the text, you should now be in developer mode._
_4. Go back to the dashboard._
_5. Go to Update Center._
_6. You should now see a 'Latest dev version' panel, tap on the download button next to it._
_7. If the file ('Vertex_Client_PE_Dev.js') was downloaded correctly, you should be able to import it into BlockLauncher. Make sure to disable the old version (v3.1) first._

**Comment by SWPlaysMC** [comment] 2019-10-13 22:59
Thank you!
It has worked.
Also, it still says that 3.1 is the latest version, even if I have those features + more mods + dev. options.

**Comment by SWPlaysMC** [comment] 2019-10-13 23:19
Edit: Reopened to make it easier to find.

**Comment by Vertex-Client** [comment] 2019-10-13 23:30
Yes, you should ignore the update notifications in dev builds, as we never changed that to include dev versions. It shows v3.1 because that is the latest release. While changing it is not a priority, I will definitely take it into account for the v3.2 release.

**Comment by Vertex-Client** [comment] 2019-10-13 23:48
I will now close this issue, as the main bug should be fixed. If you have any further questions, feel free to ask.

**Closed as completed by Vertex-Client** 2019-10-13 23:48 UTC
Labels: bug

**Comment by SWPlaysMC** [comment] 2019-10-14 20:19
Ok.
(Off-Topic)

**Comment by Vertex-Client** [comment] 2019-10-14 22:41
> 
> 
> Yes, you should ignore the update notifications in dev builds, as we never changed that to include dev versions. It shows v3.1 because that is the latest release. While changing it is not a priority, I will definitely take it into account for the v3.2 release.

@SWPlaysMC I decided to add this functionality. Feel free to test the latest dev version, you know how to get it. 
_(Off-topic)_
